name: server

networks:
  db-net:
    name: db-net
    driver: bridge
  app-net:
    name: app-net
    driver: bridge

services:
  mysql:
    extends:
      file: ./infra/mysql/compose.yml
      service: mysql
    networks: [db-net]
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks: [app-net, db-net]
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/board?characterEncoding=UTF-8&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=application
      - SPRING_DATASOURCE_PASSWORD=application
    depends_on:
      mysql:
        condition: service_healthy